version: '3.3'
services:
  web-service:
    depends_on:
      - model-service
    image: liviobue/mdm_buergli1_project2:latest
    ports:
      - "80:8082"
    restart: always
 
  model-service:
    image: liviobue/djl-serving-buergli1:latest
    restart: always
    ports:
      - "8080:8080"